// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: ibc/applications/transfer/v2/token.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

/** Token defines a struct which represents a token to be transferred. */
export interface Token {
  /** the token denomination */
  denom:
    | Denom
    | undefined;
  /** the token amount to be transferred */
  amount: string;
}

/** Denom holds the base denom of a Token and a trace of the chains it was sent through. */
export interface Denom {
  /** the base token denomination */
  base: string;
  /** the trace of the token */
  trace: Trace[];
}

/**
 * Trace represents the portID and channelID the token arrived through.
 * When a token is sent to a new chain, the portID and channelID of the
 * destination chain are added to a token's trace.
 */
export interface Trace {
  port_id: string;
  channel_id: string;
}

function createBaseToken(): Token {
  return { denom: undefined, amount: "" };
}

export const Token = {
  $type: "ibc.applications.transfer.v2.Token" as const,

  encode(message: Token, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.denom !== undefined) {
      Denom.encode(message.denom, writer.uint32(10).fork()).ldelim();
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Token {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.denom = Denom.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Token {
    return {
      denom: isSet(object.denom) ? Denom.fromJSON(object.denom) : undefined,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
    };
  },

  toJSON(message: Token): unknown {
    const obj: any = {};
    if (message.denom !== undefined) {
      obj.denom = Denom.toJSON(message.denom);
    }
    if (message.amount !== undefined) {
      obj.amount = message.amount;
    }
    return obj;
  },

  create(base?: DeepPartial<Token>): Token {
    return Token.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Token>): Token {
    const message = createBaseToken();
    message.denom = (object.denom !== undefined && object.denom !== null) ? Denom.fromPartial(object.denom) : undefined;
    message.amount = object.amount ?? "";
    return message;
  },
};

function createBaseDenom(): Denom {
  return { base: "", trace: [] };
}

export const Denom = {
  $type: "ibc.applications.transfer.v2.Denom" as const,

  encode(message: Denom, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.base !== "") {
      writer.uint32(10).string(message.base);
    }
    for (const v of message.trace) {
      Trace.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Denom {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDenom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.base = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.trace.push(Trace.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Denom {
    return {
      base: isSet(object.base) ? globalThis.String(object.base) : "",
      trace: globalThis.Array.isArray(object?.trace) ? object.trace.map((e: any) => Trace.fromJSON(e)) : [],
    };
  },

  toJSON(message: Denom): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = message.base;
    }
    if (message.trace?.length) {
      obj.trace = message.trace.map((e) => Trace.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Denom>): Denom {
    return Denom.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Denom>): Denom {
    const message = createBaseDenom();
    message.base = object.base ?? "";
    message.trace = object.trace?.map((e) => Trace.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTrace(): Trace {
  return { port_id: "", channel_id: "" };
}

export const Trace = {
  $type: "ibc.applications.transfer.v2.Trace" as const,

  encode(message: Trace, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.port_id !== "") {
      writer.uint32(10).string(message.port_id);
    }
    if (message.channel_id !== "") {
      writer.uint32(18).string(message.channel_id);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Trace {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrace();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.port_id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.channel_id = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trace {
    return {
      port_id: isSet(object.port_id) ? globalThis.String(object.port_id) : "",
      channel_id: isSet(object.channel_id) ? globalThis.String(object.channel_id) : "",
    };
  },

  toJSON(message: Trace): unknown {
    const obj: any = {};
    if (message.port_id !== undefined) {
      obj.port_id = message.port_id;
    }
    if (message.channel_id !== undefined) {
      obj.channel_id = message.channel_id;
    }
    return obj;
  },

  create(base?: DeepPartial<Trace>): Trace {
    return Trace.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Trace>): Trace {
    const message = createBaseTrace();
    message.port_id = object.port_id ?? "";
    message.channel_id = object.channel_id ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
